package HibernateUtil;
// Generated 22-apr-2013 23:08:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festivals generated by hbm2java
 */
public class Festivals  implements java.io.Serializable {


     private Integer festId;
     private String festNaam;
     private String festLocatie;
     private Date festDatum;
     private int festDuur;
     private Date festEinddatum;
     private String festUrl;
     private Set<Tickettypesperfestival> tickettypesperfestivals = new HashSet<Tickettypesperfestival>(0);

    public Festivals() {
    }

	
    public Festivals(String festNaam, String festLocatie, Date festDatum, int festDuur, Date festEinddatum) {
        this.festNaam = festNaam;
        this.festLocatie = festLocatie;
        this.festDatum = festDatum;
        this.festDuur = festDuur;
        this.festEinddatum = festEinddatum;
    }
    public Festivals(String festNaam, String festLocatie, Date festDatum, int festDuur, Date festEinddatum, String festUrl, Set<Tickettypesperfestival> tickettypesperfestivals) {
       this.festNaam = festNaam;
       this.festLocatie = festLocatie;
       this.festDatum = festDatum;
       this.festDuur = festDuur;
       this.festEinddatum = festEinddatum;
       this.festUrl = festUrl;
       this.tickettypesperfestivals = tickettypesperfestivals;
    }
   
    public Integer getFestId() {
        return this.festId;
    }
    
    public void setFestId(Integer festId) {
        this.festId = festId;
    }
    public String getFestNaam() {
        return this.festNaam;
    }
    
    public void setFestNaam(String festNaam) {
        this.festNaam = festNaam;
    }
    public String getFestLocatie() {
        return this.festLocatie;
    }
    
    public void setFestLocatie(String festLocatie) {
        this.festLocatie = festLocatie;
    }
    public Date getFestDatum() {
        return this.festDatum;
    }
    
    public void setFestDatum(Date festDatum) {
        this.festDatum = festDatum;
    }
    public int getFestDuur() {
        return this.festDuur;
    }
    
    public void setFestDuur(int festDuur) {
        this.festDuur = festDuur;
    }
    public Date getFestEinddatum() {
        return this.festEinddatum;
    }
    
    public void setFestEinddatum(Date festEinddatum) {
        this.festEinddatum = festEinddatum;
    }
    public String getFestUrl() {
        return this.festUrl;
    }
    
    public void setFestUrl(String festUrl) {
        this.festUrl = festUrl;
    }
    public Set<Tickettypesperfestival> getTickettypesperfestivals() {
        return this.tickettypesperfestivals;
    }
    
    public void setTickettypesperfestivals(Set<Tickettypesperfestival> tickettypesperfestivals) {
        this.tickettypesperfestivals = tickettypesperfestivals;
    }




}


