package HibernateUtil;
// Generated 22-apr-2013 23:08:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Geregistreerdegebruikers generated by hbm2java
 */
public class Geregistreerdegebruikers  implements java.io.Serializable {


     private Integer gebrId;
     private String gebrNaam;
     private String gebrAdres;
     private String gebrWachtwoord;
     private Date gebrGebDat;

    public Geregistreerdegebruikers() {
    }

    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, String gebrWachtwoord, Date gebrGebDat) {
       this.gebrNaam = gebrNaam;
       this.gebrAdres = gebrAdres;
       this.gebrWachtwoord = gebrWachtwoord;
       this.gebrGebDat = gebrGebDat;
    }
   
    public Integer getGebrId() {
        return this.gebrId;
    }
    
    public void setGebrId(Integer gebrId) {
        this.gebrId = gebrId;
    }
    public String getGebrNaam() {
        return this.gebrNaam;
    }
    
    public void setGebrNaam(String gebrNaam) {
        this.gebrNaam = gebrNaam;
    }
    public String getGebrAdres() {
        return this.gebrAdres;
    }
    
    public void setGebrAdres(String gebrAdres) {
        this.gebrAdres = gebrAdres;
    }
    public String getGebrWachtwoord() {
        return this.gebrWachtwoord;
    }
    
    public void setGebrWachtwoord(String gebrWachtwoord) {
        this.gebrWachtwoord = gebrWachtwoord;
    }
    public Date getGebrGebDat() {
        return this.gebrGebDat;
    }
    
    public void setGebrGebDat(Date gebrGebDat) {
        this.gebrGebDat = gebrGebDat;
    }




}


